language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: iamjoncannonexampleapp # see README
  api_key:
    secure: VOFpVgVz6snCIzXthHVtL7ryXzPTCd9ZxHPhXaSPI/MizT+RYml5mbFoFg2DY9ZJBNvHAiFp0tHQ3CRID5Z/FTZyI7iLUI5f1JIYZrQQWX4SnO2JVOruzAQI6csazsWS8qvlXVuGeOEX/WCaboAslTAPSEjmkWEm5VevRP0JXhp/z+K1R8K59PHyKJZvFcwnmcza/EPMrvW0jXdHDZ2rqNawtnhyHTM5iwsFWIuOB0a3LW7TSJ8PCzSJeWmSsHpn1jma5M05YVDfK5iUqpHCLTopR3BgznluK1DpyOzRoirenEgn2M5TA25YBo5/Jd0kHIMk6BciOAkElv+wpIMLi9Mg/3AUAZNNQxGD/JSNceIs/qGu62EaQeTPNDvJhlsXfizAHR560dJTTKJ1yLWThgSn3s7KTRwKZ0YpsPOnMpJ5JpQVZMljEFu/62+fh7yFFgKGKmw2XzyHNnGV3rO1MWoRqRHLRyZ6BVpxpYjRd9wP6X+iOo7PUiPFR6tiriOuCWxqU+vCSXFKCdZIRMyYWFje17lpMCzdrR8EzlP4g513rLzLaXKwmz21RiGYbHnQAcvwRaStmLMRDr/5NfLfi0Y3A64TvQTmKSlgrSC7cXFiOplcoPfyy/DbgfMqEh/adx2403eSoO8fnuGoHejtf0G2e26DpRf8RWEj5VTvaAI=
